#!/usr/bin/env bash
#
# Builds the body of a "release: <base> ← <head>" pull request.
#
#   usage: release-notes.sh <head-branch> <base-branch> [repo-url]
#   e.g.   release-notes.sh dev staging https://github.com/Pickriders/backend-api
#
# The headline list is ONLY squash-merged pull requests. A squash merge lands on
# the target branch as a single-parent commit whose subject GitHub suffixes with
# the PR number — "feat(wallet): funding terms (#207)". Two parents means a merge
# commit; no PR number means a direct push. Those are counted and collapsed
# underneath so the total always reconciles, but they are not the headline list.
#
# Writes markdown to stdout. Needs full history: actions/checkout fetch-depth: 0.

set -euo pipefail

HEAD_BRANCH="${1:?usage: release-notes.sh <head-branch> <base-branch> [repo-url]}"
BASE_BRANCH="${2:?usage: release-notes.sh <head-branch> <base-branch> [repo-url]}"
REPO_URL="${3:-}"
REPO_URL="${REPO_URL%/}"

# Prefer the remote-tracking ref; fall back to a local branch name.
resolve() {
  if git rev-parse --verify --quiet "origin/$1" >/dev/null 2>&1; then echo "origin/$1"
  else echo "$1"; fi
}
HEAD_REF="$(resolve "$HEAD_BRANCH")"
BASE_REF="$(resolve "$BASE_BRANCH")"
RANGE="${BASE_REF}..${HEAD_REF}"

squash_lines=""; squash_count=0
other_lines="";  other_count=0

while IFS=$'\t' read -r parents subject author; do
  [ -z "${subject:-}" ] && continue
  # shellcheck disable=SC2086
  set -- $parents; nparents=$#

  if [ "$nparents" -ge 2 ]; then
    other_lines+="- ${subject} — ${author} \`merge commit\`"$'\n'
    other_count=$((other_count + 1))
  elif [[ "$subject" =~ \(#([0-9]+)\)[[:space:]]*$ ]]; then
    num="${BASH_REMATCH[1]}"
    title="$(printf '%s' "$subject" | sed -E 's/[[:space:]]*\(#[0-9]+\)[[:space:]]*$//')"
    if [ -n "$REPO_URL" ]; then link="[#${num}](${REPO_URL}/pull/${num})"; else link="#${num}"; fi
    squash_lines+="- **${title}** — ${author} (${link})"$'\n'
    squash_count=$((squash_count + 1))
  else
    other_lines+="- ${subject} — ${author} \`direct commit\`"$'\n'
    other_count=$((other_count + 1))
  fi
done < <(git log --reverse --format='%p%x09%s%x09%an' "$RANGE" 2>/dev/null || true)

total=$((squash_count + other_count))

printf '## release: %s ← %s\n\n' "$BASE_BRANCH" "$HEAD_BRANCH"

if [ "$total" -eq 0 ]; then
  printf '_Nothing to release — `%s` already contains everything in `%s`._\n' "$BASE_BRANCH" "$HEAD_BRANCH"
else
  printf '### Squash-merged pull requests (%s)\n\n' "$squash_count"
  if [ "$squash_count" -gt 0 ]; then
    printf '%s\n' "$squash_lines"
  else
    printf '_No squash-merged pull requests in this range._\n\n'
  fi

  if [ "$other_count" -gt 0 ]; then
    printf '<details>\n<summary>%s other commit(s) — merge commits and direct pushes</summary>\n\n%s\n</details>\n' \
      "$other_count" "$other_lines"
  fi
fi

printf '\n---\n<sub>%s commit(s) in `%s..%s` — %s squash-merged, %s other. Generated by `.github/scripts/release-notes.sh` at %s.</sub>\n' \
  "$total" "$BASE_BRANCH" "$HEAD_BRANCH" "$squash_count" "$other_count" "$(date -u '+%Y-%m-%d %H:%M UTC')"
