import type { Metadata } from "next";
import { Layout } from "@/components/layouts";
import { Suspense } from "react";
import { LogoutModal } from "./LogoutModal";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-primary-foreground min-h-screen">
      <Layout.Header />
      <div className="grid grid-cols-[auto_1fr]">
        <div>
          <Layout.Sidebar />
        </div>
        <main className="pt-6 px-7 pb-10">
          <div className="2xl:max-w-[73rem] xl:max-w-[70rem] mx-auto ">
            {children}
          </div>
        </main>
      </div>
      {/* Modals */}
      <Suspense>
        <LogoutModal />
      </Suspense>
    </div>
  );
}
