import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/main.scss";
import { UI } from "@/components/common";
import { Layout } from "@/components/layouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UI.Container element={"section"} backgroundColor="#F3F3F3">
          <UI.Container display="flex" maxWidth={"1600px"} margin={"0 auto"}>
            <Layout.Sidebar />
            <UI.Container>{children}</UI.Container>
          </UI.Container>
        </UI.Container>
      </body>
    </html>
  );
}
