import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { clashDisplay, faktumTest, montserrat } from "@/styles/fonts";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        clashDisplay.variable,
        montserrat.variable,
        faktumTest.variable
      )}
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          // storageKey="pickriders-theme"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
