import type { Metadata } from "next";
import { UI } from "@/components/common";
import { Layout } from "@/components/layouts";
import "@/styles/layout/_grid.scss";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-primary-foreground min-h-screen">
      <Layout.Header />
      <div className="grid grid-cols-[auto_1fr]">
        <div>
          <Layout.Sidebar />
        </div>
        <main className="pt-6 px-7 pb-10">{children}</main>
      </div>
    </div>
  );
}

// @DEPERICATED DESIGN
// <UI.Container width={"100%"} element={"section"} backgroundColor="#F3F3F3">
//   <UI.Container display="flex" minHeight={"100vh"}>
//     <Layout.Sidebar />

//     <UI.Container className="main" element={"main"}>
//       <Layout.Topbar />
//       <UI.Container maxWidth={1202} margin={"0 auto"}>
//         {children}
//       </UI.Container>
//     </UI.Container>
//   </UI.Container>
// </UI.Container>
