import type { Metadata } from "next";
import { UI } from "@/components/common";
import { Layout } from "@/components/layouts";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UI.Container width={"100%"} element={"section"} backgroundColor="#F3F3F3">
      <UI.Container display="flex" minHeight={"100vh"}>
        <Layout.Sidebar />
        <UI.Container width={"100%"}>
          <Layout.Topbar />
          {children}
        </UI.Container>
      </UI.Container>
    </UI.Container>
  );
}
