import type { Metadata } from "next";
import { UI } from "@/components/common";
import { Layout } from "@/components/layouts";
import "@/styles/layout/_grid.scss";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UI.Container width={"100%"} element={"section"} backgroundColor="#F3F3F3">
      <UI.Container display="flex" minHeight={"100vh"}>
        <Layout.Sidebar />

        <UI.Container className="main" element={"main"}>
          <Layout.Topbar />
          <UI.Container maxWidth={1202} margin={"0 auto"}>
            {children}
          </UI.Container>
        </UI.Container>
      </UI.Container>
    </UI.Container>
  );
}
